services:
  webapp.ui:
    image: webapp.ui
    container_name: web_ui
    build:
      context: .
      dockerfile: WebApp.UI/Dockerfile
    ports:
      - 80:80
  webapp.api:
    image: webapp.api
    container_name: web_app
    build:
      context: .
      dockerfile: WebApp.Api/Dockerfile
  db:
    image: postgres
    container_name: pg_sql
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 123456