@Api_HostAddress = https://localhost:8080

### Get player by ID

Get {{Api_HostAddress}}/api/v1/players/1

### Get all players

Get {{Api_HostAddress}}/api/v1/players

### Create a player

Post {{Api_HostAddress}}/api/v1/players
Content-Type: application/json

{
  "email": "test@mail.com",
  "firstName": "Michael",
  "lastName": "Myers",
  "street": "45 Lampkin Lane",
  "city": "Haddonfield",
  "country": "USA",
  "zipCode": "32342"
}

### Update the player

Put {{Api_HostAddress}}/api/v1/players
Content-Type: application/json

{
  "id": 1,
  "firstName": "Michael",
  "lastName": "Myers",
  "street": "45 Lampkin Lane",
  "city": "Haddonfield",
  "country": "USA",
  "zipCode": "66666"
}

### Delete the player

Delete {{Api_HostAddress}}/api/v1/players/1
